// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8_6GTgI4H0mPwbXUWI9juEmgR0rWtNRQ',
    appId: '1:974990202941:web:b37c35633fb807b8a0f254',
    messagingSenderId: '974990202941',
    projectId: 'instagram2-1c0a2',
    authDomain: 'instagram2-1c0a2.firebaseapp.com',
    storageBucket: 'instagram2-1c0a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJiMC56hOubO8bKfIlHCh_6ot4skK6fsk',
    appId: '1:974990202941:android:47fc15c71544cda9a0f254',
    messagingSenderId: '974990202941',
    projectId: 'instagram2-1c0a2',
    storageBucket: 'instagram2-1c0a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMuF6Ob9aYFnjPv7xMFs11ytzOuX1yCY',
    appId: '1:974990202941:ios:3ea5fddbf40f27daa0f254',
    messagingSenderId: '974990202941',
    projectId: 'instagram2-1c0a2',
    storageBucket: 'instagram2-1c0a2.appspot.com',
    iosBundleId: 'com.example.insta02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdMuF6Ob9aYFnjPv7xMFs11ytzOuX1yCY',
    appId: '1:974990202941:ios:20fbb3fb96b21d8da0f254',
    messagingSenderId: '974990202941',
    projectId: 'instagram2-1c0a2',
    storageBucket: 'instagram2-1c0a2.appspot.com',
    iosBundleId: 'com.example.insta02.RunnerTests',
  );
}
